# TSP config
xmax: 100
ymax: 100
n_nodes: 15

# Animation config
fps: 2
n_frames: 100

# ACS config
n_steps: 1000  # number of steps for each ant
n_agent: 10
learning_rate: 0.2
local_pheromone_update: -1  # -1 means auto pick
pheromone_impact: 2
distance_impact: 1
exploration_rate: 0.1